/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SobreRouteImport } from './routes/sobre'
import { Route as FavoritosRouteImport } from './routes/favoritos'
import { Route as EntrarRouteImport } from './routes/entrar'
import { Route as ContatoRouteImport } from './routes/contato'
import { Route as ComprarRouteImport } from './routes/comprar'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AlugarRouteImport } from './routes/alugar'
import { Route as PortalRouteRouteImport } from './routes/portal/route'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ImovelIdRouteImport } from './routes/imovel.$id'
import { Route as ImoveisRecentesRouteImport } from './routes/imoveis/recentes'
import { Route as AuthenticatedAppRouteImport } from './routes/_authenticated/app'
import { Route as PortalSindicoIndexRouteImport } from './routes/portal/sindico/index'
import { Route as PortalProprietarioIndexRouteImport } from './routes/portal/proprietario/index'
import { Route as PortalLocatarioIndexRouteImport } from './routes/portal/locatario/index'
import { Route as AuthenticatedAppIndexRouteImport } from './routes/_authenticated/app.index'
import { Route as PortalSindicoSolicitacoesRouteImport } from './routes/portal/sindico/solicitacoes'
import { Route as PortalSindicoCondominiosRouteImport } from './routes/portal/sindico/condominios'
import { Route as PortalProprietarioPerfilRouteImport } from './routes/portal/proprietario/perfil'
import { Route as PortalProprietarioImoveisRouteImport } from './routes/portal/proprietario/imoveis'
import { Route as PortalProprietarioFinanceiroRouteImport } from './routes/portal/proprietario/financeiro'
import { Route as PortalProprietarioDocumentosRouteImport } from './routes/portal/proprietario/documentos'
import { Route as PortalProprietarioContratosRouteImport } from './routes/portal/proprietario/contratos'
import { Route as PortalLocatarioPerfilRouteImport } from './routes/portal/locatario/perfil'
import { Route as PortalLocatarioDocumentosRouteImport } from './routes/portal/locatario/documentos'
import { Route as PortalLocatarioContratoRouteImport } from './routes/portal/locatario/contrato'
import { Route as PortalLocatarioChamadosRouteImport } from './routes/portal/locatario/chamados'
import { Route as PortalLocatarioBoletosRouteImport } from './routes/portal/locatario/boletos'
import { Route as AuthenticatedAppVisitasRouteImport } from './routes/_authenticated/app.visitas'
import { Route as AuthenticatedAppPropostasRouteImport } from './routes/_authenticated/app.propostas'
import { Route as AuthenticatedAppLeadsRouteImport } from './routes/_authenticated/app.leads'
import { Route as AuthenticatedAppImoveisRouteImport } from './routes/_authenticated/app.imoveis'
import { Route as AuthenticatedAppDashboardRouteImport } from './routes/_authenticated/app.dashboard'
import { Route as AuthenticatedAppContratosRouteImport } from './routes/_authenticated/app.contratos'
import { Route as AuthenticatedAppBoletosRouteImport } from './routes/_authenticated/app.boletos'
import { Route as AuthenticatedAppAcessosRouteImport } from './routes/_authenticated/app.acessos'

const SobreRoute = SobreRouteImport.update({
  id: '/sobre',
  path: '/sobre',
  getParentRoute: () => rootRouteImport,
} as any)
const FavoritosRoute = FavoritosRouteImport.update({
  id: '/favoritos',
  path: '/favoritos',
  getParentRoute: () => rootRouteImport,
} as any)
const EntrarRoute = EntrarRouteImport.update({
  id: '/entrar',
  path: '/entrar',
  getParentRoute: () => rootRouteImport,
} as any)
const ContatoRoute = ContatoRouteImport.update({
  id: '/contato',
  path: '/contato',
  getParentRoute: () => rootRouteImport,
} as any)
const ComprarRoute = ComprarRouteImport.update({
  id: '/comprar',
  path: '/comprar',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AlugarRoute = AlugarRouteImport.update({
  id: '/alugar',
  path: '/alugar',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalRouteRoute = PortalRouteRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ImovelIdRoute = ImovelIdRouteImport.update({
  id: '/imovel/$id',
  path: '/imovel/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ImoveisRecentesRoute = ImoveisRecentesRouteImport.update({
  id: '/imoveis/recentes',
  path: '/imoveis/recentes',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAppRoute = AuthenticatedAppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const PortalSindicoIndexRoute = PortalSindicoIndexRouteImport.update({
  id: '/sindico/',
  path: '/sindico/',
  getParentRoute: () => PortalRouteRoute,
} as any)
const PortalProprietarioIndexRoute = PortalProprietarioIndexRouteImport.update({
  id: '/proprietario/',
  path: '/proprietario/',
  getParentRoute: () => PortalRouteRoute,
} as any)
const PortalLocatarioIndexRoute = PortalLocatarioIndexRouteImport.update({
  id: '/locatario/',
  path: '/locatario/',
  getParentRoute: () => PortalRouteRoute,
} as any)
const AuthenticatedAppIndexRoute = AuthenticatedAppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const PortalSindicoSolicitacoesRoute =
  PortalSindicoSolicitacoesRouteImport.update({
    id: '/sindico/solicitacoes',
    path: '/sindico/solicitacoes',
    getParentRoute: () => PortalRouteRoute,
  } as any)
const PortalSindicoCondominiosRoute =
  PortalSindicoCondominiosRouteImport.update({
    id: '/sindico/condominios',
    path: '/sindico/condominios',
    getParentRoute: () => PortalRouteRoute,
  } as any)
const PortalProprietarioPerfilRoute =
  PortalProprietarioPerfilRouteImport.update({
    id: '/proprietario/perfil',
    path: '/proprietario/perfil',
    getParentRoute: () => PortalRouteRoute,
  } as any)
const PortalProprietarioImoveisRoute =
  PortalProprietarioImoveisRouteImport.update({
    id: '/proprietario/imoveis',
    path: '/proprietario/imoveis',
    getParentRoute: () => PortalRouteRoute,
  } as any)
const PortalProprietarioFinanceiroRoute =
  PortalProprietarioFinanceiroRouteImport.update({
    id: '/proprietario/financeiro',
    path: '/proprietario/financeiro',
    getParentRoute: () => PortalRouteRoute,
  } as any)
const PortalProprietarioDocumentosRoute =
  PortalProprietarioDocumentosRouteImport.update({
    id: '/proprietario/documentos',
    path: '/proprietario/documentos',
    getParentRoute: () => PortalRouteRoute,
  } as any)
const PortalProprietarioContratosRoute =
  PortalProprietarioContratosRouteImport.update({
    id: '/proprietario/contratos',
    path: '/proprietario/contratos',
    getParentRoute: () => PortalRouteRoute,
  } as any)
const PortalLocatarioPerfilRoute = PortalLocatarioPerfilRouteImport.update({
  id: '/locatario/perfil',
  path: '/locatario/perfil',
  getParentRoute: () => PortalRouteRoute,
} as any)
const PortalLocatarioDocumentosRoute =
  PortalLocatarioDocumentosRouteImport.update({
    id: '/locatario/documentos',
    path: '/locatario/documentos',
    getParentRoute: () => PortalRouteRoute,
  } as any)
const PortalLocatarioContratoRoute = PortalLocatarioContratoRouteImport.update({
  id: '/locatario/contrato',
  path: '/locatario/contrato',
  getParentRoute: () => PortalRouteRoute,
} as any)
const PortalLocatarioChamadosRoute = PortalLocatarioChamadosRouteImport.update({
  id: '/locatario/chamados',
  path: '/locatario/chamados',
  getParentRoute: () => PortalRouteRoute,
} as any)
const PortalLocatarioBoletosRoute = PortalLocatarioBoletosRouteImport.update({
  id: '/locatario/boletos',
  path: '/locatario/boletos',
  getParentRoute: () => PortalRouteRoute,
} as any)
const AuthenticatedAppVisitasRoute = AuthenticatedAppVisitasRouteImport.update({
  id: '/visitas',
  path: '/visitas',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppPropostasRoute =
  AuthenticatedAppPropostasRouteImport.update({
    id: '/propostas',
    path: '/propostas',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppLeadsRoute = AuthenticatedAppLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppImoveisRoute = AuthenticatedAppImoveisRouteImport.update({
  id: '/imoveis',
  path: '/imoveis',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppDashboardRoute =
  AuthenticatedAppDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppContratosRoute =
  AuthenticatedAppContratosRouteImport.update({
    id: '/contratos',
    path: '/contratos',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppBoletosRoute = AuthenticatedAppBoletosRouteImport.update({
  id: '/boletos',
  path: '/boletos',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppAcessosRoute = AuthenticatedAppAcessosRouteImport.update({
  id: '/acessos',
  path: '/acessos',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/portal': typeof PortalRouteRouteWithChildren
  '/alugar': typeof AlugarRoute
  '/auth': typeof AuthRoute
  '/comprar': typeof ComprarRoute
  '/contato': typeof ContatoRoute
  '/entrar': typeof EntrarRoute
  '/favoritos': typeof FavoritosRoute
  '/sobre': typeof SobreRoute
  '/app': typeof AuthenticatedAppRouteWithChildren
  '/imoveis/recentes': typeof ImoveisRecentesRoute
  '/imovel/$id': typeof ImovelIdRoute
  '/app/acessos': typeof AuthenticatedAppAcessosRoute
  '/app/boletos': typeof AuthenticatedAppBoletosRoute
  '/app/contratos': typeof AuthenticatedAppContratosRoute
  '/app/dashboard': typeof AuthenticatedAppDashboardRoute
  '/app/imoveis': typeof AuthenticatedAppImoveisRoute
  '/app/leads': typeof AuthenticatedAppLeadsRoute
  '/app/propostas': typeof AuthenticatedAppPropostasRoute
  '/app/visitas': typeof AuthenticatedAppVisitasRoute
  '/portal/locatario/boletos': typeof PortalLocatarioBoletosRoute
  '/portal/locatario/chamados': typeof PortalLocatarioChamadosRoute
  '/portal/locatario/contrato': typeof PortalLocatarioContratoRoute
  '/portal/locatario/documentos': typeof PortalLocatarioDocumentosRoute
  '/portal/locatario/perfil': typeof PortalLocatarioPerfilRoute
  '/portal/proprietario/contratos': typeof PortalProprietarioContratosRoute
  '/portal/proprietario/documentos': typeof PortalProprietarioDocumentosRoute
  '/portal/proprietario/financeiro': typeof PortalProprietarioFinanceiroRoute
  '/portal/proprietario/imoveis': typeof PortalProprietarioImoveisRoute
  '/portal/proprietario/perfil': typeof PortalProprietarioPerfilRoute
  '/portal/sindico/condominios': typeof PortalSindicoCondominiosRoute
  '/portal/sindico/solicitacoes': typeof PortalSindicoSolicitacoesRoute
  '/app/': typeof AuthenticatedAppIndexRoute
  '/portal/locatario/': typeof PortalLocatarioIndexRoute
  '/portal/proprietario/': typeof PortalProprietarioIndexRoute
  '/portal/sindico/': typeof PortalSindicoIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/portal': typeof PortalRouteRouteWithChildren
  '/alugar': typeof AlugarRoute
  '/auth': typeof AuthRoute
  '/comprar': typeof ComprarRoute
  '/contato': typeof ContatoRoute
  '/entrar': typeof EntrarRoute
  '/favoritos': typeof FavoritosRoute
  '/sobre': typeof SobreRoute
  '/imoveis/recentes': typeof ImoveisRecentesRoute
  '/imovel/$id': typeof ImovelIdRoute
  '/app/acessos': typeof AuthenticatedAppAcessosRoute
  '/app/boletos': typeof AuthenticatedAppBoletosRoute
  '/app/contratos': typeof AuthenticatedAppContratosRoute
  '/app/dashboard': typeof AuthenticatedAppDashboardRoute
  '/app/imoveis': typeof AuthenticatedAppImoveisRoute
  '/app/leads': typeof AuthenticatedAppLeadsRoute
  '/app/propostas': typeof AuthenticatedAppPropostasRoute
  '/app/visitas': typeof AuthenticatedAppVisitasRoute
  '/portal/locatario/boletos': typeof PortalLocatarioBoletosRoute
  '/portal/locatario/chamados': typeof PortalLocatarioChamadosRoute
  '/portal/locatario/contrato': typeof PortalLocatarioContratoRoute
  '/portal/locatario/documentos': typeof PortalLocatarioDocumentosRoute
  '/portal/locatario/perfil': typeof PortalLocatarioPerfilRoute
  '/portal/proprietario/contratos': typeof PortalProprietarioContratosRoute
  '/portal/proprietario/documentos': typeof PortalProprietarioDocumentosRoute
  '/portal/proprietario/financeiro': typeof PortalProprietarioFinanceiroRoute
  '/portal/proprietario/imoveis': typeof PortalProprietarioImoveisRoute
  '/portal/proprietario/perfil': typeof PortalProprietarioPerfilRoute
  '/portal/sindico/condominios': typeof PortalSindicoCondominiosRoute
  '/portal/sindico/solicitacoes': typeof PortalSindicoSolicitacoesRoute
  '/app': typeof AuthenticatedAppIndexRoute
  '/portal/locatario': typeof PortalLocatarioIndexRoute
  '/portal/proprietario': typeof PortalProprietarioIndexRoute
  '/portal/sindico': typeof PortalSindicoIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/portal': typeof PortalRouteRouteWithChildren
  '/alugar': typeof AlugarRoute
  '/auth': typeof AuthRoute
  '/comprar': typeof ComprarRoute
  '/contato': typeof ContatoRoute
  '/entrar': typeof EntrarRoute
  '/favoritos': typeof FavoritosRoute
  '/sobre': typeof SobreRoute
  '/_authenticated/app': typeof AuthenticatedAppRouteWithChildren
  '/imoveis/recentes': typeof ImoveisRecentesRoute
  '/imovel/$id': typeof ImovelIdRoute
  '/_authenticated/app/acessos': typeof AuthenticatedAppAcessosRoute
  '/_authenticated/app/boletos': typeof AuthenticatedAppBoletosRoute
  '/_authenticated/app/contratos': typeof AuthenticatedAppContratosRoute
  '/_authenticated/app/dashboard': typeof AuthenticatedAppDashboardRoute
  '/_authenticated/app/imoveis': typeof AuthenticatedAppImoveisRoute
  '/_authenticated/app/leads': typeof AuthenticatedAppLeadsRoute
  '/_authenticated/app/propostas': typeof AuthenticatedAppPropostasRoute
  '/_authenticated/app/visitas': typeof AuthenticatedAppVisitasRoute
  '/portal/locatario/boletos': typeof PortalLocatarioBoletosRoute
  '/portal/locatario/chamados': typeof PortalLocatarioChamadosRoute
  '/portal/locatario/contrato': typeof PortalLocatarioContratoRoute
  '/portal/locatario/documentos': typeof PortalLocatarioDocumentosRoute
  '/portal/locatario/perfil': typeof PortalLocatarioPerfilRoute
  '/portal/proprietario/contratos': typeof PortalProprietarioContratosRoute
  '/portal/proprietario/documentos': typeof PortalProprietarioDocumentosRoute
  '/portal/proprietario/financeiro': typeof PortalProprietarioFinanceiroRoute
  '/portal/proprietario/imoveis': typeof PortalProprietarioImoveisRoute
  '/portal/proprietario/perfil': typeof PortalProprietarioPerfilRoute
  '/portal/sindico/condominios': typeof PortalSindicoCondominiosRoute
  '/portal/sindico/solicitacoes': typeof PortalSindicoSolicitacoesRoute
  '/_authenticated/app/': typeof AuthenticatedAppIndexRoute
  '/portal/locatario/': typeof PortalLocatarioIndexRoute
  '/portal/proprietario/': typeof PortalProprietarioIndexRoute
  '/portal/sindico/': typeof PortalSindicoIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/portal'
    | '/alugar'
    | '/auth'
    | '/comprar'
    | '/contato'
    | '/entrar'
    | '/favoritos'
    | '/sobre'
    | '/app'
    | '/imoveis/recentes'
    | '/imovel/$id'
    | '/app/acessos'
    | '/app/boletos'
    | '/app/contratos'
    | '/app/dashboard'
    | '/app/imoveis'
    | '/app/leads'
    | '/app/propostas'
    | '/app/visitas'
    | '/portal/locatario/boletos'
    | '/portal/locatario/chamados'
    | '/portal/locatario/contrato'
    | '/portal/locatario/documentos'
    | '/portal/locatario/perfil'
    | '/portal/proprietario/contratos'
    | '/portal/proprietario/documentos'
    | '/portal/proprietario/financeiro'
    | '/portal/proprietario/imoveis'
    | '/portal/proprietario/perfil'
    | '/portal/sindico/condominios'
    | '/portal/sindico/solicitacoes'
    | '/app/'
    | '/portal/locatario/'
    | '/portal/proprietario/'
    | '/portal/sindico/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/portal'
    | '/alugar'
    | '/auth'
    | '/comprar'
    | '/contato'
    | '/entrar'
    | '/favoritos'
    | '/sobre'
    | '/imoveis/recentes'
    | '/imovel/$id'
    | '/app/acessos'
    | '/app/boletos'
    | '/app/contratos'
    | '/app/dashboard'
    | '/app/imoveis'
    | '/app/leads'
    | '/app/propostas'
    | '/app/visitas'
    | '/portal/locatario/boletos'
    | '/portal/locatario/chamados'
    | '/portal/locatario/contrato'
    | '/portal/locatario/documentos'
    | '/portal/locatario/perfil'
    | '/portal/proprietario/contratos'
    | '/portal/proprietario/documentos'
    | '/portal/proprietario/financeiro'
    | '/portal/proprietario/imoveis'
    | '/portal/proprietario/perfil'
    | '/portal/sindico/condominios'
    | '/portal/sindico/solicitacoes'
    | '/app'
    | '/portal/locatario'
    | '/portal/proprietario'
    | '/portal/sindico'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/portal'
    | '/alugar'
    | '/auth'
    | '/comprar'
    | '/contato'
    | '/entrar'
    | '/favoritos'
    | '/sobre'
    | '/_authenticated/app'
    | '/imoveis/recentes'
    | '/imovel/$id'
    | '/_authenticated/app/acessos'
    | '/_authenticated/app/boletos'
    | '/_authenticated/app/contratos'
    | '/_authenticated/app/dashboard'
    | '/_authenticated/app/imoveis'
    | '/_authenticated/app/leads'
    | '/_authenticated/app/propostas'
    | '/_authenticated/app/visitas'
    | '/portal/locatario/boletos'
    | '/portal/locatario/chamados'
    | '/portal/locatario/contrato'
    | '/portal/locatario/documentos'
    | '/portal/locatario/perfil'
    | '/portal/proprietario/contratos'
    | '/portal/proprietario/documentos'
    | '/portal/proprietario/financeiro'
    | '/portal/proprietario/imoveis'
    | '/portal/proprietario/perfil'
    | '/portal/sindico/condominios'
    | '/portal/sindico/solicitacoes'
    | '/_authenticated/app/'
    | '/portal/locatario/'
    | '/portal/proprietario/'
    | '/portal/sindico/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  PortalRouteRoute: typeof PortalRouteRouteWithChildren
  AlugarRoute: typeof AlugarRoute
  AuthRoute: typeof AuthRoute
  ComprarRoute: typeof ComprarRoute
  ContatoRoute: typeof ContatoRoute
  EntrarRoute: typeof EntrarRoute
  FavoritosRoute: typeof FavoritosRoute
  SobreRoute: typeof SobreRoute
  ImoveisRecentesRoute: typeof ImoveisRecentesRoute
  ImovelIdRoute: typeof ImovelIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sobre': {
      id: '/sobre'
      path: '/sobre'
      fullPath: '/sobre'
      preLoaderRoute: typeof SobreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favoritos': {
      id: '/favoritos'
      path: '/favoritos'
      fullPath: '/favoritos'
      preLoaderRoute: typeof FavoritosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entrar': {
      id: '/entrar'
      path: '/entrar'
      fullPath: '/entrar'
      preLoaderRoute: typeof EntrarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contato': {
      id: '/contato'
      path: '/contato'
      fullPath: '/contato'
      preLoaderRoute: typeof ContatoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comprar': {
      id: '/comprar'
      path: '/comprar'
      fullPath: '/comprar'
      preLoaderRoute: typeof ComprarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alugar': {
      id: '/alugar'
      path: '/alugar'
      fullPath: '/alugar'
      preLoaderRoute: typeof AlugarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal': {
      id: '/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof PortalRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/imovel/$id': {
      id: '/imovel/$id'
      path: '/imovel/$id'
      fullPath: '/imovel/$id'
      preLoaderRoute: typeof ImovelIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/imoveis/recentes': {
      id: '/imoveis/recentes'
      path: '/imoveis/recentes'
      fullPath: '/imoveis/recentes'
      preLoaderRoute: typeof ImoveisRecentesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/app': {
      id: '/_authenticated/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AuthenticatedAppRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/portal/sindico/': {
      id: '/portal/sindico/'
      path: '/sindico'
      fullPath: '/portal/sindico/'
      preLoaderRoute: typeof PortalSindicoIndexRouteImport
      parentRoute: typeof PortalRouteRoute
    }
    '/portal/proprietario/': {
      id: '/portal/proprietario/'
      path: '/proprietario'
      fullPath: '/portal/proprietario/'
      preLoaderRoute: typeof PortalProprietarioIndexRouteImport
      parentRoute: typeof PortalRouteRoute
    }
    '/portal/locatario/': {
      id: '/portal/locatario/'
      path: '/locatario'
      fullPath: '/portal/locatario/'
      preLoaderRoute: typeof PortalLocatarioIndexRouteImport
      parentRoute: typeof PortalRouteRoute
    }
    '/_authenticated/app/': {
      id: '/_authenticated/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AuthenticatedAppIndexRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/portal/sindico/solicitacoes': {
      id: '/portal/sindico/solicitacoes'
      path: '/sindico/solicitacoes'
      fullPath: '/portal/sindico/solicitacoes'
      preLoaderRoute: typeof PortalSindicoSolicitacoesRouteImport
      parentRoute: typeof PortalRouteRoute
    }
    '/portal/sindico/condominios': {
      id: '/portal/sindico/condominios'
      path: '/sindico/condominios'
      fullPath: '/portal/sindico/condominios'
      preLoaderRoute: typeof PortalSindicoCondominiosRouteImport
      parentRoute: typeof PortalRouteRoute
    }
    '/portal/proprietario/perfil': {
      id: '/portal/proprietario/perfil'
      path: '/proprietario/perfil'
      fullPath: '/portal/proprietario/perfil'
      preLoaderRoute: typeof PortalProprietarioPerfilRouteImport
      parentRoute: typeof PortalRouteRoute
    }
    '/portal/proprietario/imoveis': {
      id: '/portal/proprietario/imoveis'
      path: '/proprietario/imoveis'
      fullPath: '/portal/proprietario/imoveis'
      preLoaderRoute: typeof PortalProprietarioImoveisRouteImport
      parentRoute: typeof PortalRouteRoute
    }
    '/portal/proprietario/financeiro': {
      id: '/portal/proprietario/financeiro'
      path: '/proprietario/financeiro'
      fullPath: '/portal/proprietario/financeiro'
      preLoaderRoute: typeof PortalProprietarioFinanceiroRouteImport
      parentRoute: typeof PortalRouteRoute
    }
    '/portal/proprietario/documentos': {
      id: '/portal/proprietario/documentos'
      path: '/proprietario/documentos'
      fullPath: '/portal/proprietario/documentos'
      preLoaderRoute: typeof PortalProprietarioDocumentosRouteImport
      parentRoute: typeof PortalRouteRoute
    }
    '/portal/proprietario/contratos': {
      id: '/portal/proprietario/contratos'
      path: '/proprietario/contratos'
      fullPath: '/portal/proprietario/contratos'
      preLoaderRoute: typeof PortalProprietarioContratosRouteImport
      parentRoute: typeof PortalRouteRoute
    }
    '/portal/locatario/perfil': {
      id: '/portal/locatario/perfil'
      path: '/locatario/perfil'
      fullPath: '/portal/locatario/perfil'
      preLoaderRoute: typeof PortalLocatarioPerfilRouteImport
      parentRoute: typeof PortalRouteRoute
    }
    '/portal/locatario/documentos': {
      id: '/portal/locatario/documentos'
      path: '/locatario/documentos'
      fullPath: '/portal/locatario/documentos'
      preLoaderRoute: typeof PortalLocatarioDocumentosRouteImport
      parentRoute: typeof PortalRouteRoute
    }
    '/portal/locatario/contrato': {
      id: '/portal/locatario/contrato'
      path: '/locatario/contrato'
      fullPath: '/portal/locatario/contrato'
      preLoaderRoute: typeof PortalLocatarioContratoRouteImport
      parentRoute: typeof PortalRouteRoute
    }
    '/portal/locatario/chamados': {
      id: '/portal/locatario/chamados'
      path: '/locatario/chamados'
      fullPath: '/portal/locatario/chamados'
      preLoaderRoute: typeof PortalLocatarioChamadosRouteImport
      parentRoute: typeof PortalRouteRoute
    }
    '/portal/locatario/boletos': {
      id: '/portal/locatario/boletos'
      path: '/locatario/boletos'
      fullPath: '/portal/locatario/boletos'
      preLoaderRoute: typeof PortalLocatarioBoletosRouteImport
      parentRoute: typeof PortalRouteRoute
    }
    '/_authenticated/app/visitas': {
      id: '/_authenticated/app/visitas'
      path: '/visitas'
      fullPath: '/app/visitas'
      preLoaderRoute: typeof AuthenticatedAppVisitasRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/propostas': {
      id: '/_authenticated/app/propostas'
      path: '/propostas'
      fullPath: '/app/propostas'
      preLoaderRoute: typeof AuthenticatedAppPropostasRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/leads': {
      id: '/_authenticated/app/leads'
      path: '/leads'
      fullPath: '/app/leads'
      preLoaderRoute: typeof AuthenticatedAppLeadsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/imoveis': {
      id: '/_authenticated/app/imoveis'
      path: '/imoveis'
      fullPath: '/app/imoveis'
      preLoaderRoute: typeof AuthenticatedAppImoveisRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/dashboard': {
      id: '/_authenticated/app/dashboard'
      path: '/dashboard'
      fullPath: '/app/dashboard'
      preLoaderRoute: typeof AuthenticatedAppDashboardRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/contratos': {
      id: '/_authenticated/app/contratos'
      path: '/contratos'
      fullPath: '/app/contratos'
      preLoaderRoute: typeof AuthenticatedAppContratosRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/boletos': {
      id: '/_authenticated/app/boletos'
      path: '/boletos'
      fullPath: '/app/boletos'
      preLoaderRoute: typeof AuthenticatedAppBoletosRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/acessos': {
      id: '/_authenticated/app/acessos'
      path: '/acessos'
      fullPath: '/app/acessos'
      preLoaderRoute: typeof AuthenticatedAppAcessosRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
  }
}

interface AuthenticatedAppRouteChildren {
  AuthenticatedAppAcessosRoute: typeof AuthenticatedAppAcessosRoute
  AuthenticatedAppBoletosRoute: typeof AuthenticatedAppBoletosRoute
  AuthenticatedAppContratosRoute: typeof AuthenticatedAppContratosRoute
  AuthenticatedAppDashboardRoute: typeof AuthenticatedAppDashboardRoute
  AuthenticatedAppImoveisRoute: typeof AuthenticatedAppImoveisRoute
  AuthenticatedAppLeadsRoute: typeof AuthenticatedAppLeadsRoute
  AuthenticatedAppPropostasRoute: typeof AuthenticatedAppPropostasRoute
  AuthenticatedAppVisitasRoute: typeof AuthenticatedAppVisitasRoute
  AuthenticatedAppIndexRoute: typeof AuthenticatedAppIndexRoute
}

const AuthenticatedAppRouteChildren: AuthenticatedAppRouteChildren = {
  AuthenticatedAppAcessosRoute: AuthenticatedAppAcessosRoute,
  AuthenticatedAppBoletosRoute: AuthenticatedAppBoletosRoute,
  AuthenticatedAppContratosRoute: AuthenticatedAppContratosRoute,
  AuthenticatedAppDashboardRoute: AuthenticatedAppDashboardRoute,
  AuthenticatedAppImoveisRoute: AuthenticatedAppImoveisRoute,
  AuthenticatedAppLeadsRoute: AuthenticatedAppLeadsRoute,
  AuthenticatedAppPropostasRoute: AuthenticatedAppPropostasRoute,
  AuthenticatedAppVisitasRoute: AuthenticatedAppVisitasRoute,
  AuthenticatedAppIndexRoute: AuthenticatedAppIndexRoute,
}

const AuthenticatedAppRouteWithChildren =
  AuthenticatedAppRoute._addFileChildren(AuthenticatedAppRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAppRoute: typeof AuthenticatedAppRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAppRoute: AuthenticatedAppRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface PortalRouteRouteChildren {
  PortalLocatarioBoletosRoute: typeof PortalLocatarioBoletosRoute
  PortalLocatarioChamadosRoute: typeof PortalLocatarioChamadosRoute
  PortalLocatarioContratoRoute: typeof PortalLocatarioContratoRoute
  PortalLocatarioDocumentosRoute: typeof PortalLocatarioDocumentosRoute
  PortalLocatarioPerfilRoute: typeof PortalLocatarioPerfilRoute
  PortalProprietarioContratosRoute: typeof PortalProprietarioContratosRoute
  PortalProprietarioDocumentosRoute: typeof PortalProprietarioDocumentosRoute
  PortalProprietarioFinanceiroRoute: typeof PortalProprietarioFinanceiroRoute
  PortalProprietarioImoveisRoute: typeof PortalProprietarioImoveisRoute
  PortalProprietarioPerfilRoute: typeof PortalProprietarioPerfilRoute
  PortalSindicoCondominiosRoute: typeof PortalSindicoCondominiosRoute
  PortalSindicoSolicitacoesRoute: typeof PortalSindicoSolicitacoesRoute
  PortalLocatarioIndexRoute: typeof PortalLocatarioIndexRoute
  PortalProprietarioIndexRoute: typeof PortalProprietarioIndexRoute
  PortalSindicoIndexRoute: typeof PortalSindicoIndexRoute
}

const PortalRouteRouteChildren: PortalRouteRouteChildren = {
  PortalLocatarioBoletosRoute: PortalLocatarioBoletosRoute,
  PortalLocatarioChamadosRoute: PortalLocatarioChamadosRoute,
  PortalLocatarioContratoRoute: PortalLocatarioContratoRoute,
  PortalLocatarioDocumentosRoute: PortalLocatarioDocumentosRoute,
  PortalLocatarioPerfilRoute: PortalLocatarioPerfilRoute,
  PortalProprietarioContratosRoute: PortalProprietarioContratosRoute,
  PortalProprietarioDocumentosRoute: PortalProprietarioDocumentosRoute,
  PortalProprietarioFinanceiroRoute: PortalProprietarioFinanceiroRoute,
  PortalProprietarioImoveisRoute: PortalProprietarioImoveisRoute,
  PortalProprietarioPerfilRoute: PortalProprietarioPerfilRoute,
  PortalSindicoCondominiosRoute: PortalSindicoCondominiosRoute,
  PortalSindicoSolicitacoesRoute: PortalSindicoSolicitacoesRoute,
  PortalLocatarioIndexRoute: PortalLocatarioIndexRoute,
  PortalProprietarioIndexRoute: PortalProprietarioIndexRoute,
  PortalSindicoIndexRoute: PortalSindicoIndexRoute,
}

const PortalRouteRouteWithChildren = PortalRouteRoute._addFileChildren(
  PortalRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  PortalRouteRoute: PortalRouteRouteWithChildren,
  AlugarRoute: AlugarRoute,
  AuthRoute: AuthRoute,
  ComprarRoute: ComprarRoute,
  ContatoRoute: ContatoRoute,
  EntrarRoute: EntrarRoute,
  FavoritosRoute: FavoritosRoute,
  SobreRoute: SobreRoute,
  ImoveisRecentesRoute: ImoveisRecentesRoute,
  ImovelIdRoute: ImovelIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
