// This file is automatically generated. Do not edit it directly.
import { createMiddleware } from '@tanstack/react-start'
import { supabase } from './client'

function hasSupabaseEnv() {
  const hasValue = (value: unknown) =>
    typeof value === 'string' &&
    value.trim() !== '' &&
    value !== 'undefined' &&
    value !== 'null';

  return hasValue(import.meta.env.VITE_SUPABASE_URL || import.meta.env.SUPABASE_URL) &&
    hasValue(import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || import.meta.env.SUPABASE_PUBLISHABLE_KEY);
}

// Must be registered as a global `functionMiddleware` in `src/start.ts`; otherwise
// the browser never attaches the bearer token to serverFn RPCs.
export const attachSupabaseAuth = createMiddleware({ type: 'function' }).client(
  async ({ next }) => {
    if (!hasSupabaseEnv()) return next();

    const { data } = await supabase.auth.getSession()
    const token = data.session?.access_token
    return next({
      headers: token ?{ Authorization: `Bearer ${token}` } : {},
    })
  },
)
